Revert "Add derived UsbTransport class with USB reset method"
This reverts commit 0f1f29650dae7af1577ef2613eebb4a11cd07f09 [formerly ceb7cbf5fde0ff26a35d442135d01e52b0ef0771].

Reason for revert: Broke mac builds:
system/core/fastboot/usb_osx.cpp:513:35: error: use of undeclared identifier 'USB_TRANSACTION_TIMEOUT'
USB_TRANSACTION_TIMEOUT, USB_TRANSACTION_TIMEOUT);
^

Change-Id: Ibe2f9ff2d5c63f9d33f4bd6d9ba962604cf8caeb

Former-commit-id: ec1542f22dba42f66453133eb03c5dfc3685902f